package com.example.projectfinal.utils

const val BASE_URL="http:/192.168.1.110:4000/v1/api/"
const val AUTHORIZATION = "Bearer "
const val AUTHORIZATION_TAG = "AUTHORIZATION"
const val ACCESS_TOKEN = "ACCESS_TOKEN"
const val PREFS_NAME = "PREFERENCES"
const val FIRST_TIME = "FIRST_TIME"
const val ROLE = "ROLE"
const val ADMIN = "admin"
const val MEMBER = "member"
const val MOD = "moderator"
const val GROUP_ID = "group_id"
const val TOPIC_ID = "topic_id"
const val USERNAME = "username"
const val USERNAME_ID = "username_id"
const val NAME_GROUP = "name_group"
const val NAME_TOPIC = "name_topic"
const val POST_ID = "post_id"
const val FEED_ID = "feed_id"